<?php
/**
 * AdresType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Model;
use \KvK\ObjectSerializer;

/**
 * AdresType Class Doc Comment
 *
 * @category Class
 * @description Bezoekadres of postadres
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdresType
{
    /**
     * Possible values of this enum
     */
    public const BEZOEKADRES = 'bezoekadres';

    public const POSTADRES = 'postadres';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BEZOEKADRES,
            self::POSTADRES
        ];
    }
}


