<?php
/**
 * BaseSignalType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Model;

use \ArrayAccess;
use \KvK\ObjectSerializer;

/**
 * BaseSignalType Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BaseSignalType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BaseSignalType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bericht_id' => 'string',
        'heeft_betrekking_op' => '\KvK\Model\MaatschappelijkeActiviteitType',
        'registratie_id' => 'string',
        'registratie_tijdstip' => '\DateTime',
        'signaal_type' => '\KvK\Model\SignaalType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bericht_id' => null,
        'heeft_betrekking_op' => null,
        'registratie_id' => null,
        'registratie_tijdstip' => 'date-time',
        'signaal_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bericht_id' => false,
        'heeft_betrekking_op' => false,
        'registratie_id' => false,
        'registratie_tijdstip' => false,
        'signaal_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bericht_id' => 'berichtId',
        'heeft_betrekking_op' => 'heeftBetrekkingOp',
        'registratie_id' => 'registratieId',
        'registratie_tijdstip' => 'registratieTijdstip',
        'signaal_type' => 'signaalType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bericht_id' => 'setBerichtId',
        'heeft_betrekking_op' => 'setHeeftBetrekkingOp',
        'registratie_id' => 'setRegistratieId',
        'registratie_tijdstip' => 'setRegistratieTijdstip',
        'signaal_type' => 'setSignaalType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bericht_id' => 'getBerichtId',
        'heeft_betrekking_op' => 'getHeeftBetrekkingOp',
        'registratie_id' => 'getRegistratieId',
        'registratie_tijdstip' => 'getRegistratieTijdstip',
        'signaal_type' => 'getSignaalType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bericht_id', $data ?? [], null);
        $this->setIfExists('heeft_betrekking_op', $data ?? [], null);
        $this->setIfExists('registratie_id', $data ?? [], null);
        $this->setIfExists('registratie_tijdstip', $data ?? [], null);
        $this->setIfExists('signaal_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bericht_id'] === null) {
            $invalidProperties[] = "'bericht_id' can't be null";
        }
        if ($this->container['heeft_betrekking_op'] === null) {
            $invalidProperties[] = "'heeft_betrekking_op' can't be null";
        }
        if ($this->container['registratie_id'] === null) {
            $invalidProperties[] = "'registratie_id' can't be null";
        }
        if ($this->container['registratie_tijdstip'] === null) {
            $invalidProperties[] = "'registratie_tijdstip' can't be null";
        }
        if ($this->container['signaal_type'] === null) {
            $invalidProperties[] = "'signaal_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bericht_id
     *
     * @return string
     */
    public function getBerichtId()
    {
        return $this->container['bericht_id'];
    }

    /**
     * Sets bericht_id
     *
     * @param string $bericht_id bericht_id
     *
     * @return self
     */
    public function setBerichtId($bericht_id)
    {
        if (is_null($bericht_id)) {
            throw new \InvalidArgumentException('non-nullable bericht_id cannot be null');
        }
        $this->container['bericht_id'] = $bericht_id;

        return $this;
    }

    /**
     * Gets heeft_betrekking_op
     *
     * @return \KvK\Model\MaatschappelijkeActiviteitType
     */
    public function getHeeftBetrekkingOp()
    {
        return $this->container['heeft_betrekking_op'];
    }

    /**
     * Sets heeft_betrekking_op
     *
     * @param \KvK\Model\MaatschappelijkeActiviteitType $heeft_betrekking_op heeft_betrekking_op
     *
     * @return self
     */
    public function setHeeftBetrekkingOp($heeft_betrekking_op)
    {
        if (is_null($heeft_betrekking_op)) {
            throw new \InvalidArgumentException('non-nullable heeft_betrekking_op cannot be null');
        }
        $this->container['heeft_betrekking_op'] = $heeft_betrekking_op;

        return $this;
    }

    /**
     * Gets registratie_id
     *
     * @return string
     */
    public function getRegistratieId()
    {
        return $this->container['registratie_id'];
    }

    /**
     * Sets registratie_id
     *
     * @param string $registratie_id registratie_id
     *
     * @return self
     */
    public function setRegistratieId($registratie_id)
    {
        if (is_null($registratie_id)) {
            throw new \InvalidArgumentException('non-nullable registratie_id cannot be null');
        }
        $this->container['registratie_id'] = $registratie_id;

        return $this;
    }

    /**
     * Gets registratie_tijdstip
     *
     * @return \DateTime
     */
    public function getRegistratieTijdstip()
    {
        return $this->container['registratie_tijdstip'];
    }

    /**
     * Sets registratie_tijdstip
     *
     * @param \DateTime $registratie_tijdstip registratie_tijdstip
     *
     * @return self
     */
    public function setRegistratieTijdstip($registratie_tijdstip)
    {
        if (is_null($registratie_tijdstip)) {
            throw new \InvalidArgumentException('non-nullable registratie_tijdstip cannot be null');
        }
        $this->container['registratie_tijdstip'] = $registratie_tijdstip;

        return $this;
    }

    /**
     * Gets signaal_type
     *
     * @return \KvK\Model\SignaalType
     */
    public function getSignaalType()
    {
        return $this->container['signaal_type'];
    }

    /**
     * Sets signaal_type
     *
     * @param \KvK\Model\SignaalType $signaal_type signaal_type
     *
     * @return self
     */
    public function setSignaalType($signaal_type)
    {
        if (is_null($signaal_type)) {
            throw new \InvalidArgumentException('non-nullable signaal_type cannot be null');
        }
        $this->container['signaal_type'] = $signaal_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


