<?php
/**
 * MaatschappelijkeActiviteitType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Model;

use \ArrayAccess;
use \KvK\ObjectSerializer;

/**
 * MaatschappelijkeActiviteitType Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MaatschappelijkeActiviteitType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MaatschappelijkeActiviteitType';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'heeft_als_eigenaar' => '\KvK\Model\EigenaarType',
        'kvk_nummer' => 'string',
        'non_mailing' => 'bool',
        'totaal_werkzame_personen' => 'int',
        'wordt_uitgeoefend_in' => '\KvK\Model\VestigingType[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'heeft_als_eigenaar' => null,
        'kvk_nummer' => null,
        'non_mailing' => null,
        'totaal_werkzame_personen' => null,
        'wordt_uitgeoefend_in' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'heeft_als_eigenaar' => false,
        'kvk_nummer' => false,
        'non_mailing' => false,
        'totaal_werkzame_personen' => false,
        'wordt_uitgeoefend_in' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'heeft_als_eigenaar' => 'heeftAlsEigenaar',
        'kvk_nummer' => 'kvkNummer',
        'non_mailing' => 'nonMailing',
        'totaal_werkzame_personen' => 'totaalWerkzamePersonen',
        'wordt_uitgeoefend_in' => 'wordtUitgeoefendIn'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'heeft_als_eigenaar' => 'setHeeftAlsEigenaar',
        'kvk_nummer' => 'setKvkNummer',
        'non_mailing' => 'setNonMailing',
        'totaal_werkzame_personen' => 'setTotaalWerkzamePersonen',
        'wordt_uitgeoefend_in' => 'setWordtUitgeoefendIn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'heeft_als_eigenaar' => 'getHeeftAlsEigenaar',
        'kvk_nummer' => 'getKvkNummer',
        'non_mailing' => 'getNonMailing',
        'totaal_werkzame_personen' => 'getTotaalWerkzamePersonen',
        'wordt_uitgeoefend_in' => 'getWordtUitgeoefendIn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('heeft_als_eigenaar', $data ?? [], null);
        $this->setIfExists('kvk_nummer', $data ?? [], null);
        $this->setIfExists('non_mailing', $data ?? [], null);
        $this->setIfExists('totaal_werkzame_personen', $data ?? [], null);
        $this->setIfExists('wordt_uitgeoefend_in', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['kvk_nummer'] === null) {
            $invalidProperties[] = "'kvk_nummer' can't be null";
        }
        if ($this->container['non_mailing'] === null) {
            $invalidProperties[] = "'non_mailing' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets heeft_als_eigenaar
     *
     * @return \KvK\Model\EigenaarType|null
     */
    public function getHeeftAlsEigenaar()
    {
        return $this->container['heeft_als_eigenaar'];
    }

    /**
     * Sets heeft_als_eigenaar
     *
     * @param \KvK\Model\EigenaarType|null $heeft_als_eigenaar heeft_als_eigenaar
     *
     * @return self
     */
    public function setHeeftAlsEigenaar($heeft_als_eigenaar)
    {
        if (is_null($heeft_als_eigenaar)) {
            throw new \InvalidArgumentException('non-nullable heeft_als_eigenaar cannot be null');
        }
        $this->container['heeft_als_eigenaar'] = $heeft_als_eigenaar;

        return $this;
    }

    /**
     * Gets kvk_nummer
     *
     * @return string
     */
    public function getKvkNummer()
    {
        return $this->container['kvk_nummer'];
    }

    /**
     * Sets kvk_nummer
     *
     * @param string $kvk_nummer kvk_nummer
     *
     * @return self
     */
    public function setKvkNummer($kvk_nummer)
    {
        if (is_null($kvk_nummer)) {
            throw new \InvalidArgumentException('non-nullable kvk_nummer cannot be null');
        }
        $this->container['kvk_nummer'] = $kvk_nummer;

        return $this;
    }

    /**
     * Gets non_mailing
     *
     * @return bool
     */
    public function getNonMailing()
    {
        return $this->container['non_mailing'];
    }

    /**
     * Sets non_mailing
     *
     * @param bool $non_mailing non_mailing
     *
     * @return self
     */
    public function setNonMailing($non_mailing)
    {
        if (is_null($non_mailing)) {
            throw new \InvalidArgumentException('non-nullable non_mailing cannot be null');
        }
        $this->container['non_mailing'] = $non_mailing;

        return $this;
    }

    /**
     * Gets totaal_werkzame_personen
     *
     * @return int|null
     */
    public function getTotaalWerkzamePersonen()
    {
        return $this->container['totaal_werkzame_personen'];
    }

    /**
     * Sets totaal_werkzame_personen
     *
     * @param int|null $totaal_werkzame_personen totaal_werkzame_personen
     *
     * @return self
     */
    public function setTotaalWerkzamePersonen($totaal_werkzame_personen)
    {
        if (is_null($totaal_werkzame_personen)) {
            throw new \InvalidArgumentException('non-nullable totaal_werkzame_personen cannot be null');
        }
        $this->container['totaal_werkzame_personen'] = $totaal_werkzame_personen;

        return $this;
    }

    /**
     * Gets wordt_uitgeoefend_in
     *
     * @return \KvK\Model\VestigingType[]|null
     */
    public function getWordtUitgeoefendIn()
    {
        return $this->container['wordt_uitgeoefend_in'];
    }

    /**
     * Sets wordt_uitgeoefend_in
     *
     * @param \KvK\Model\VestigingType[]|null $wordt_uitgeoefend_in wordt_uitgeoefend_in
     *
     * @return self
     */
    public function setWordtUitgeoefendIn($wordt_uitgeoefend_in)
    {
        if (is_null($wordt_uitgeoefend_in)) {
            throw new \InvalidArgumentException('non-nullable wordt_uitgeoefend_in cannot be null');
        }
        $this->container['wordt_uitgeoefend_in'] = $wordt_uitgeoefend_in;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


