<?php
/**
 * ResultaatItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Model;

use \ArrayAccess;
use \KvK\ObjectSerializer;

/**
 * ResultaatItem Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResultaatItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResultaatItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kvk_nummer' => 'string',
        'rsin' => 'string',
        'vestigingsnummer' => 'string',
        'naam' => 'string',
        'adres' => '\KvK\Model\Adres1',
        'type' => 'string',
        'actief' => 'string',
        'vervallen_naam' => 'string',
        '_links' => 'array<string,\KvK\Model\Link1>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kvk_nummer' => null,
        'rsin' => null,
        'vestigingsnummer' => null,
        'naam' => null,
        'adres' => null,
        'type' => null,
        'actief' => null,
        'vervallen_naam' => null,
        '_links' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kvk_nummer' => false,
        'rsin' => false,
        'vestigingsnummer' => false,
        'naam' => false,
        'adres' => false,
        'type' => false,
        'actief' => false,
        'vervallen_naam' => false,
        '_links' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kvk_nummer' => 'kvkNummer',
        'rsin' => 'rsin',
        'vestigingsnummer' => 'vestigingsnummer',
        'naam' => 'naam',
        'adres' => 'adres',
        'type' => 'type',
        'actief' => 'actief',
        'vervallen_naam' => 'vervallenNaam',
        '_links' => '_links'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kvk_nummer' => 'setKvkNummer',
        'rsin' => 'setRsin',
        'vestigingsnummer' => 'setVestigingsnummer',
        'naam' => 'setNaam',
        'adres' => 'setAdres',
        'type' => 'setType',
        'actief' => 'setActief',
        'vervallen_naam' => 'setVervallenNaam',
        '_links' => 'setLinks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kvk_nummer' => 'getKvkNummer',
        'rsin' => 'getRsin',
        'vestigingsnummer' => 'getVestigingsnummer',
        'naam' => 'getNaam',
        'adres' => 'getAdres',
        'type' => 'getType',
        'actief' => 'getActief',
        'vervallen_naam' => 'getVervallenNaam',
        '_links' => 'getLinks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kvk_nummer', $data ?? [], null);
        $this->setIfExists('rsin', $data ?? [], null);
        $this->setIfExists('vestigingsnummer', $data ?? [], null);
        $this->setIfExists('naam', $data ?? [], null);
        $this->setIfExists('adres', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('actief', $data ?? [], null);
        $this->setIfExists('vervallen_naam', $data ?? [], null);
        $this->setIfExists('_links', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kvk_nummer
     *
     * @return string|null
     */
    public function getKvkNummer()
    {
        return $this->container['kvk_nummer'];
    }

    /**
     * Sets kvk_nummer
     *
     * @param string|null $kvk_nummer Nederlands Kamer van Koophandel nummer dat bestaat uit 8 cijfers
     *
     * @return self
     */
    public function setKvkNummer($kvk_nummer)
    {
        if (is_null($kvk_nummer)) {
            throw new \InvalidArgumentException('non-nullable kvk_nummer cannot be null');
        }
        $this->container['kvk_nummer'] = $kvk_nummer;

        return $this;
    }

    /**
     * Gets rsin
     *
     * @return string|null
     */
    public function getRsin()
    {
        return $this->container['rsin'];
    }

    /**
     * Sets rsin
     *
     * @param string|null $rsin Rechtspersonen Samenwerkingsverbanden Informatie Nummer dat bestaat uit 9 cijfers
     *
     * @return self
     */
    public function setRsin($rsin)
    {
        if (is_null($rsin)) {
            throw new \InvalidArgumentException('non-nullable rsin cannot be null');
        }
        $this->container['rsin'] = $rsin;

        return $this;
    }

    /**
     * Gets vestigingsnummer
     *
     * @return string|null
     */
    public function getVestigingsnummer()
    {
        return $this->container['vestigingsnummer'];
    }

    /**
     * Sets vestigingsnummer
     *
     * @param string|null $vestigingsnummer Vestigingsnummer dat bestaat uit 12 cijfers
     *
     * @return self
     */
    public function setVestigingsnummer($vestigingsnummer)
    {
        if (is_null($vestigingsnummer)) {
            throw new \InvalidArgumentException('non-nullable vestigingsnummer cannot be null');
        }
        $this->container['vestigingsnummer'] = $vestigingsnummer;

        return $this;
    }

    /**
     * Gets naam
     *
     * @return string|null
     */
    public function getNaam()
    {
        return $this->container['naam'];
    }

    /**
     * Sets naam
     *
     * @param string|null $naam De naam waaronder een vestiging of rechtspersoon handelt
     *
     * @return self
     */
    public function setNaam($naam)
    {
        if (is_null($naam)) {
            throw new \InvalidArgumentException('non-nullable naam cannot be null');
        }
        $this->container['naam'] = $naam;

        return $this;
    }

    /**
     * Gets adres
     *
     * @return \KvK\Model\Adres1|null
     */
    public function getAdres()
    {
        return $this->container['adres'];
    }

    /**
     * Sets adres
     *
     * @param \KvK\Model\Adres1|null $adres adres
     *
     * @return self
     */
    public function setAdres($adres)
    {
        if (is_null($adres)) {
            throw new \InvalidArgumentException('non-nullable adres cannot be null');
        }
        $this->container['adres'] = $adres;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type hoofdvestiging/nevenvestiging/rechtspersoon
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets actief
     *
     * @return string|null
     */
    public function getActief()
    {
        return $this->container['actief'];
    }

    /**
     * Sets actief
     *
     * @param string|null $actief Indicatie of inschrijving actief is
     *
     * @return self
     */
    public function setActief($actief)
    {
        if (is_null($actief)) {
            throw new \InvalidArgumentException('non-nullable actief cannot be null');
        }
        $this->container['actief'] = $actief;

        return $this;
    }

    /**
     * Gets vervallen_naam
     *
     * @return string|null
     */
    public function getVervallenNaam()
    {
        return $this->container['vervallen_naam'];
    }

    /**
     * Sets vervallen_naam
     *
     * @param string|null $vervallen_naam Bevat de vervallen naam waaronder een vestiging of rechtspersoon heeft gehandeld
     *
     * @return self
     */
    public function setVervallenNaam($vervallen_naam)
    {
        if (is_null($vervallen_naam)) {
            throw new \InvalidArgumentException('non-nullable vervallen_naam cannot be null');
        }
        $this->container['vervallen_naam'] = $vervallen_naam;

        return $this;
    }

    /**
     * Gets _links
     *
     * @return array<string,\KvK\Model\Link1>|null
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param array<string,\KvK\Model\Link1>|null $_links _links
     *
     * @return self
     */
    public function setLinks($_links)
    {
        if (is_null($_links)) {
            throw new \InvalidArgumentException('non-nullable _links cannot be null');
        }
        $this->container['_links'] = $_links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


