<?php
/**
 * SignaalType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Model;
use \KvK\ObjectSerializer;

/**
 * SignaalType Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SignaalType
{
    /**
     * Possible values of this enum
     */
    public const SIGNAAL_GEWIJZIGDE_INSCHRIJVING = 'SignaalGewijzigdeInschrijving';

    public const SIGNAAL_NIEUWE_INSCHRIJVING = 'SignaalNieuweInschrijving';

    public const SIGNAAL_GEWIJZIGDE_VESTIGING = 'SignaalGewijzigdeVestiging';

    public const SIGNAAL_BEEINDIGING_2025_01 = 'SignaalBeeindiging_2025_01';

    public const SIGNAAL_RECHTSVORMWIJZIGING_2025_01 = 'SignaalRechtsvormwijziging_2025_01';

    public const SIGNAAL_VOORTZETTING_EN_OVERDRACHT_2025_01 = 'SignaalVoortzettingEnOverdracht_2025_01';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SIGNAAL_GEWIJZIGDE_INSCHRIJVING,
            self::SIGNAAL_NIEUWE_INSCHRIJVING,
            self::SIGNAAL_GEWIJZIGDE_VESTIGING,
            self::SIGNAAL_BEEINDIGING_2025_01,
            self::SIGNAAL_RECHTSVORMWIJZIGING_2025_01,
            self::SIGNAAL_VOORTZETTING_EN_OVERDRACHT_2025_01
        ];
    }
}


