<?php
/**
 * AbonnementApi
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use KvK\ApiException;
use KvK\Configuration;
use KvK\FormDataProcessor;
use KvK\HeaderSelector;
use KvK\ObjectSerializer;

/**
 * AbonnementApi Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AbonnementApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'listAbonnementen' => [
            'application/json',
        ],
        'listSignalsByAbonnementId' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listAbonnementen
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAbonnementen'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\AbonnementenHalJsonResponseType|\KvK\Model\ProblemDetail|\KvK\Model\ProblemDetail
     */
    public function listAbonnementen(string $contentType = self::contentTypes['listAbonnementen'][0])
    {
        list($response) = $this->listAbonnementenWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listAbonnementenWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAbonnementen'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\AbonnementenHalJsonResponseType|\KvK\Model\ProblemDetail|\KvK\Model\ProblemDetail, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAbonnementenWithHttpInfo(string $contentType = self::contentTypes['listAbonnementen'][0])
    {
        $request = $this->listAbonnementenRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\AbonnementenHalJsonResponseType',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\ProblemDetail',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\ProblemDetail',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\AbonnementenHalJsonResponseType',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\AbonnementenHalJsonResponseType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\ProblemDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\ProblemDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listAbonnementenAsync
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAbonnementen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAbonnementenAsync(string $contentType = self::contentTypes['listAbonnementen'][0])
    {
        return $this->listAbonnementenAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAbonnementenAsyncWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAbonnementen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAbonnementenAsyncWithHttpInfo(string $contentType = self::contentTypes['listAbonnementen'][0])
    {
        $returnType = '\KvK\Model\AbonnementenHalJsonResponseType';
        $request = $this->listAbonnementenRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAbonnementen'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAbonnementen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAbonnementenRequest(string $contentType = self::contentTypes['listAbonnementen'][0])
    {


        $resourcePath = '/v1/abonnementen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSignalsByAbonnementId
     *
     * @param  string $abonnement_id abonnement id (required)
     * @param  \DateTime|null $vanaf de vanaf datum-tijd (optional)
     * @param  \DateTime|null $tot de tot datum-tijd (optional)
     * @param  int|null $pagina Geeft aan welke pagina je op wilt vragen. Start vanaf pagina 1 (optional, default to 1)
     * @param  int|null $aantal Aantal zoekresultaten per pagina. (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSignalsByAbonnementId'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\PagedSignalenHalJsonType|\KvK\Model\ProblemDetail|\KvK\Model\ProblemDetail
     */
    public function listSignalsByAbonnementId($abonnement_id, $vanaf = null, $tot = null, $pagina = 1, $aantal = 100, string $contentType = self::contentTypes['listSignalsByAbonnementId'][0])
    {
        list($response) = $this->listSignalsByAbonnementIdWithHttpInfo($abonnement_id, $vanaf, $tot, $pagina, $aantal, $contentType);
        return $response;
    }

    /**
     * Operation listSignalsByAbonnementIdWithHttpInfo
     *
     * @param  string $abonnement_id abonnement id (required)
     * @param  \DateTime|null $vanaf de vanaf datum-tijd (optional)
     * @param  \DateTime|null $tot de tot datum-tijd (optional)
     * @param  int|null $pagina Geeft aan welke pagina je op wilt vragen. Start vanaf pagina 1 (optional, default to 1)
     * @param  int|null $aantal Aantal zoekresultaten per pagina. (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSignalsByAbonnementId'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\PagedSignalenHalJsonType|\KvK\Model\ProblemDetail|\KvK\Model\ProblemDetail, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSignalsByAbonnementIdWithHttpInfo($abonnement_id, $vanaf = null, $tot = null, $pagina = 1, $aantal = 100, string $contentType = self::contentTypes['listSignalsByAbonnementId'][0])
    {
        $request = $this->listSignalsByAbonnementIdRequest($abonnement_id, $vanaf, $tot, $pagina, $aantal, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\PagedSignalenHalJsonType',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\ProblemDetail',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\ProblemDetail',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\PagedSignalenHalJsonType',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\PagedSignalenHalJsonType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\ProblemDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\ProblemDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listSignalsByAbonnementIdAsync
     *
     * @param  string $abonnement_id abonnement id (required)
     * @param  \DateTime|null $vanaf de vanaf datum-tijd (optional)
     * @param  \DateTime|null $tot de tot datum-tijd (optional)
     * @param  int|null $pagina Geeft aan welke pagina je op wilt vragen. Start vanaf pagina 1 (optional, default to 1)
     * @param  int|null $aantal Aantal zoekresultaten per pagina. (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSignalsByAbonnementId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSignalsByAbonnementIdAsync($abonnement_id, $vanaf = null, $tot = null, $pagina = 1, $aantal = 100, string $contentType = self::contentTypes['listSignalsByAbonnementId'][0])
    {
        return $this->listSignalsByAbonnementIdAsyncWithHttpInfo($abonnement_id, $vanaf, $tot, $pagina, $aantal, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSignalsByAbonnementIdAsyncWithHttpInfo
     *
     * @param  string $abonnement_id abonnement id (required)
     * @param  \DateTime|null $vanaf de vanaf datum-tijd (optional)
     * @param  \DateTime|null $tot de tot datum-tijd (optional)
     * @param  int|null $pagina Geeft aan welke pagina je op wilt vragen. Start vanaf pagina 1 (optional, default to 1)
     * @param  int|null $aantal Aantal zoekresultaten per pagina. (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSignalsByAbonnementId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSignalsByAbonnementIdAsyncWithHttpInfo($abonnement_id, $vanaf = null, $tot = null, $pagina = 1, $aantal = 100, string $contentType = self::contentTypes['listSignalsByAbonnementId'][0])
    {
        $returnType = '\KvK\Model\PagedSignalenHalJsonType';
        $request = $this->listSignalsByAbonnementIdRequest($abonnement_id, $vanaf, $tot, $pagina, $aantal, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSignalsByAbonnementId'
     *
     * @param  string $abonnement_id abonnement id (required)
     * @param  \DateTime|null $vanaf de vanaf datum-tijd (optional)
     * @param  \DateTime|null $tot de tot datum-tijd (optional)
     * @param  int|null $pagina Geeft aan welke pagina je op wilt vragen. Start vanaf pagina 1 (optional, default to 1)
     * @param  int|null $aantal Aantal zoekresultaten per pagina. (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSignalsByAbonnementId'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSignalsByAbonnementIdRequest($abonnement_id, $vanaf = null, $tot = null, $pagina = 1, $aantal = 100, string $contentType = self::contentTypes['listSignalsByAbonnementId'][0])
    {

        // verify the required parameter 'abonnement_id' is set
        if ($abonnement_id === null || (is_array($abonnement_id) && count($abonnement_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $abonnement_id when calling listSignalsByAbonnementId'
            );
        }



        if ($pagina !== null && $pagina < 1) {
            throw new \InvalidArgumentException('invalid value for "$pagina" when calling AbonnementApi.listSignalsByAbonnementId, must be bigger than or equal to 1.');
        }
        
        if ($aantal !== null && $aantal > 500) {
            throw new \InvalidArgumentException('invalid value for "$aantal" when calling AbonnementApi.listSignalsByAbonnementId, must be smaller than or equal to 500.');
        }
        if ($aantal !== null && $aantal < 10) {
            throw new \InvalidArgumentException('invalid value for "$aantal" when calling AbonnementApi.listSignalsByAbonnementId, must be bigger than or equal to 10.');
        }
        

        $resourcePath = '/v1/abonnementen/{abonnementId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $vanaf,
            'vanaf', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tot,
            'tot', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pagina,
            'pagina', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $aantal,
            'aantal', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($abonnement_id !== null) {
            $resourcePath = str_replace(
                '{' . 'abonnementId' . '}',
                ObjectSerializer::toPathValue($abonnement_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
