<?php
/**
 * BasisprofielApi
 * PHP version 8.1
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KvK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use KvK\ApiException;
use KvK\Configuration;
use KvK\FormDataProcessor;
use KvK\HeaderSelector;
use KvK\ObjectSerializer;

/**
 * BasisprofielApi Class Doc Comment
 *
 * @category Class
 * @package  KvK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BasisprofielApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getBasisprofielByKvkNummer' => [
            'application/json',
        ],
        'getEigenaar' => [
            'application/json',
        ],
        'getHoofdvestiging' => [
            'application/json',
        ],
        'getVestigingen' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getBasisprofielByKvkNummer
     *
     * Voor een specifiek bedrijf basisinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBasisprofielByKvkNummer'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\Basisprofiel|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error
     */
    public function getBasisprofielByKvkNummer($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getBasisprofielByKvkNummer'][0])
    {
        list($response) = $this->getBasisprofielByKvkNummerWithHttpInfo($kvk_nummer, $geo_data, $contentType);
        return $response;
    }

    /**
     * Operation getBasisprofielByKvkNummerWithHttpInfo
     *
     * Voor een specifiek bedrijf basisinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBasisprofielByKvkNummer'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\Basisprofiel|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBasisprofielByKvkNummerWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getBasisprofielByKvkNummer'][0])
    {
        $request = $this->getBasisprofielByKvkNummerRequest($kvk_nummer, $geo_data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Basisprofiel',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\Basisprofiel',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Basisprofiel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getBasisprofielByKvkNummerAsync
     *
     * Voor een specifiek bedrijf basisinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBasisprofielByKvkNummer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBasisprofielByKvkNummerAsync($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getBasisprofielByKvkNummer'][0])
    {
        return $this->getBasisprofielByKvkNummerAsyncWithHttpInfo($kvk_nummer, $geo_data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBasisprofielByKvkNummerAsyncWithHttpInfo
     *
     * Voor een specifiek bedrijf basisinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBasisprofielByKvkNummer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBasisprofielByKvkNummerAsyncWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getBasisprofielByKvkNummer'][0])
    {
        $returnType = '\KvK\Model\Basisprofiel';
        $request = $this->getBasisprofielByKvkNummerRequest($kvk_nummer, $geo_data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBasisprofielByKvkNummer'
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBasisprofielByKvkNummer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBasisprofielByKvkNummerRequest($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getBasisprofielByKvkNummer'][0])
    {

        // verify the required parameter 'kvk_nummer' is set
        if ($kvk_nummer === null || (is_array($kvk_nummer) && count($kvk_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kvk_nummer when calling getBasisprofielByKvkNummer'
            );
        }
        if (!preg_match("/^[0-9]{8}$/", $kvk_nummer)) {
            throw new \InvalidArgumentException("invalid value for \"kvk_nummer\" when calling BasisprofielApi.getBasisprofielByKvkNummer, must conform to the pattern /^[0-9]{8}$/.");
        }
        


        $resourcePath = '/v1/basisprofielen/{kvkNummer}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $geo_data,
            'geoData', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($kvk_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'kvkNummer' . '}',
                ObjectSerializer::toPathValue($kvk_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/hal+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEigenaar
     *
     * Voor een specifiek bedrijf eigenaar informatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEigenaar'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\Eigenaar|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error
     */
    public function getEigenaar($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getEigenaar'][0])
    {
        list($response) = $this->getEigenaarWithHttpInfo($kvk_nummer, $geo_data, $contentType);
        return $response;
    }

    /**
     * Operation getEigenaarWithHttpInfo
     *
     * Voor een specifiek bedrijf eigenaar informatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEigenaar'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\Eigenaar|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEigenaarWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getEigenaar'][0])
    {
        $request = $this->getEigenaarRequest($kvk_nummer, $geo_data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Eigenaar',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\Eigenaar',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Eigenaar',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEigenaarAsync
     *
     * Voor een specifiek bedrijf eigenaar informatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEigenaar'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEigenaarAsync($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getEigenaar'][0])
    {
        return $this->getEigenaarAsyncWithHttpInfo($kvk_nummer, $geo_data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEigenaarAsyncWithHttpInfo
     *
     * Voor een specifiek bedrijf eigenaar informatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEigenaar'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEigenaarAsyncWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getEigenaar'][0])
    {
        $returnType = '\KvK\Model\Eigenaar';
        $request = $this->getEigenaarRequest($kvk_nummer, $geo_data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEigenaar'
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEigenaar'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEigenaarRequest($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getEigenaar'][0])
    {

        // verify the required parameter 'kvk_nummer' is set
        if ($kvk_nummer === null || (is_array($kvk_nummer) && count($kvk_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kvk_nummer when calling getEigenaar'
            );
        }
        if (!preg_match("/^[0-9]{8}$/", $kvk_nummer)) {
            throw new \InvalidArgumentException("invalid value for \"kvk_nummer\" when calling BasisprofielApi.getEigenaar, must conform to the pattern /^[0-9]{8}$/.");
        }
        


        $resourcePath = '/basisprofielen/{kvkNummer}/eigenaar';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $geo_data,
            'geoData', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($kvk_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'kvkNummer' . '}',
                ObjectSerializer::toPathValue($kvk_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/hal+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getHoofdvestiging
     *
     * Voor een specifiek bedrijf hoofdvestigingsinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHoofdvestiging'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\Vestiging|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error
     */
    public function getHoofdvestiging($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getHoofdvestiging'][0])
    {
        list($response) = $this->getHoofdvestigingWithHttpInfo($kvk_nummer, $geo_data, $contentType);
        return $response;
    }

    /**
     * Operation getHoofdvestigingWithHttpInfo
     *
     * Voor een specifiek bedrijf hoofdvestigingsinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHoofdvestiging'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\Vestiging|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHoofdvestigingWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getHoofdvestiging'][0])
    {
        $request = $this->getHoofdvestigingRequest($kvk_nummer, $geo_data, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Vestiging',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\Vestiging',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Vestiging',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getHoofdvestigingAsync
     *
     * Voor een specifiek bedrijf hoofdvestigingsinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHoofdvestiging'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHoofdvestigingAsync($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getHoofdvestiging'][0])
    {
        return $this->getHoofdvestigingAsyncWithHttpInfo($kvk_nummer, $geo_data, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHoofdvestigingAsyncWithHttpInfo
     *
     * Voor een specifiek bedrijf hoofdvestigingsinformatie opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHoofdvestiging'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHoofdvestigingAsyncWithHttpInfo($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getHoofdvestiging'][0])
    {
        $returnType = '\KvK\Model\Vestiging';
        $request = $this->getHoofdvestigingRequest($kvk_nummer, $geo_data, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHoofdvestiging'
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  bool|null $geo_data (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHoofdvestiging'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getHoofdvestigingRequest($kvk_nummer, $geo_data = false, string $contentType = self::contentTypes['getHoofdvestiging'][0])
    {

        // verify the required parameter 'kvk_nummer' is set
        if ($kvk_nummer === null || (is_array($kvk_nummer) && count($kvk_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kvk_nummer when calling getHoofdvestiging'
            );
        }
        if (!preg_match("/^[0-9]{8}$/", $kvk_nummer)) {
            throw new \InvalidArgumentException("invalid value for \"kvk_nummer\" when calling BasisprofielApi.getHoofdvestiging, must conform to the pattern /^[0-9]{8}$/.");
        }
        


        $resourcePath = '/basisprofielen/{kvkNummer}/hoofdvestiging';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $geo_data,
            'geoData', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($kvk_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'kvkNummer' . '}',
                ObjectSerializer::toPathValue($kvk_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/hal+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getVestigingen
     *
     * Voor een specifiek bedrijf een lijst met vestigingen opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVestigingen'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \KvK\Model\VestigingList|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error
     */
    public function getVestigingen($kvk_nummer, string $contentType = self::contentTypes['getVestigingen'][0])
    {
        list($response) = $this->getVestigingenWithHttpInfo($kvk_nummer, $contentType);
        return $response;
    }

    /**
     * Operation getVestigingenWithHttpInfo
     *
     * Voor een specifiek bedrijf een lijst met vestigingen opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVestigingen'] to see the possible values for this operation
     *
     * @throws \KvK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \KvK\Model\VestigingList|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error|\KvK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVestigingenWithHttpInfo($kvk_nummer, string $contentType = self::contentTypes['getVestigingen'][0])
    {
        $request = $this->getVestigingenRequest($kvk_nummer, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\VestigingList',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 406:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\KvK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\KvK\Model\VestigingList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\VestigingList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 406:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KvK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getVestigingenAsync
     *
     * Voor een specifiek bedrijf een lijst met vestigingen opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVestigingen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVestigingenAsync($kvk_nummer, string $contentType = self::contentTypes['getVestigingen'][0])
    {
        return $this->getVestigingenAsyncWithHttpInfo($kvk_nummer, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVestigingenAsyncWithHttpInfo
     *
     * Voor een specifiek bedrijf een lijst met vestigingen opvragen.
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVestigingen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVestigingenAsyncWithHttpInfo($kvk_nummer, string $contentType = self::contentTypes['getVestigingen'][0])
    {
        $returnType = '\KvK\Model\VestigingList';
        $request = $this->getVestigingenRequest($kvk_nummer, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVestigingen'
     *
     * @param  string $kvk_nummer Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVestigingen'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getVestigingenRequest($kvk_nummer, string $contentType = self::contentTypes['getVestigingen'][0])
    {

        // verify the required parameter 'kvk_nummer' is set
        if ($kvk_nummer === null || (is_array($kvk_nummer) && count($kvk_nummer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $kvk_nummer when calling getVestigingen'
            );
        }
        if (!preg_match("/^[0-9]{8}$/", $kvk_nummer)) {
            throw new \InvalidArgumentException("invalid value for \"kvk_nummer\" when calling BasisprofielApi.getVestigingen, must conform to the pattern /^[0-9]{8}$/.");
        }
        

        $resourcePath = '/basisprofielen/{kvkNummer}/vestigingen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($kvk_nummer !== null) {
            $resourcePath = str_replace(
                '{' . 'kvkNummer' . '}',
                ObjectSerializer::toPathValue($kvk_nummer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/hal+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $headers['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
